spring:
  datasource:
    url: jdbc:mysql://aws.connect.psdb.cloud/vixindia?sslMode=VERIFY_IDENTITY
    username: 6r5hw4sodge3do6049w7
    password: pscale_pw_XMPg2yFzrWMYmIfY6kYz2ptSFAmlSeJmwlXtt6TUwBm
    driver-class-name: com.mysql.cj.jdbc.Driver

mvc:
  view:
    prefix: /
    suffix: .html

app:
  jwtSecret: secret-key-for-jwt-token-for-vix-india-copyright 2023
  jwtExpirationInMs: 3600000

server:
  port: 8081

weatherApi:
  key: 4fcdeaa0ba0b4732b7a112545232810
  url: https://api.weatherapi.com/v1/current.json
